apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plot-listing
  namespace: metabase
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: metabase.example.com
    http:
      paths:
      - path: /metabase(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: metabase
            port:
              number: 3000
  tls:
  - hosts:
    - metabase.example.com
    secretName: metabase-tls
