apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress-separate
  namespace: plot-listing
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /metabase
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 3000
